export const VISIT_TYPES = ['KSUM', 'Incubated Company']

// Canonical purpose values — always sent to the API in English
export const PURPOSES = {
  KSUM: [
    'Financial Assistance',
    'Space Requirement',
    'Fab Lab',
    'Maker Village',
    'General Enquiry',
  ],
  'Incubated Company': [
    'Meeting',
    'Interview',
    'Internship',
    'Repair/Maintenance',
    'Other',
  ],
}

export const COPY = {
  en: {
    kicker: 'Digital Reception',
    langTitle: 'Select your language',

    visitTitle: 'Who are you here for?',
    visitSub: 'This tells us who to notify.',
    visitLabels: {
      KSUM: 'Kerala Startup Mission',
      'Incubated Company': 'Incubated Company',
    },
    visitNotes: {
      KSUM: 'Funding, space, labs and general enquiries',
      'Incubated Company': 'A startup based in this building',
    },

    detailsTitle: 'Your details',
    detailsSub: 'Please tell us who is visiting today.',
    name: 'Full name',
    namePh: 'e.g. Richard Hendrix',
    phone: 'Phone',
    phonePh: '10-digit mobile number',
    email: 'Email',
    emailPh: 'name@example.com',
    org: 'Organisation',
    orgPh: 'Company, college or institution',
    company: 'Company you are visiting',
    companyPh: 'Name of the startup',

    purposeTitle: 'Purpose of visit',
    purposeSub: 'Choose the one that fits best.',
    otherPh: 'Tell us briefly why you are here',

    reviewTitle: 'Review and confirm',
    reviewSub: 'Check the sheet below before you check in.',
    sheet: 'Visitor sheet',

    thanks: 'Thank you',
    doneSub: 'Our representative will meet you shortly. Kindly wait in the lobby area.',
    doneSubIncubated:
      'Please wait in the lobby and contact the representative from the company to proceed.',
    token: 'Token',
    checkedIn: 'Checked in',
    contactTitle: 'Your point of contact',
    escalateIn: 'Your approximate waiting time is: ',
    escalate: 'Escalate',
    escalating: 'Notifying…',
    escalated: 'Case Escalated',
    escalateFailed: 'Could not notify. Please approach the front desk.',
    loadingToken: 'Fetching your token…',
    notFoundTitle: 'Not found',
    notFoundSub: 'That check-in reference does not exist. Please check in again.',

    back: 'Back',
    continue: 'Continue',
    checkIn: 'Check in',
    checkingIn: 'Checking in',
    newVisitor: 'New visitor',

    reqVisit: 'Please choose who you are visiting.',
    reqDetails: 'Please enter your name, phone number and email.',
    reqCompany: 'Please enter the company you are visiting.',
    reqPurpose: 'Please select a purpose of visit.',
    reqOther: 'Please tell us the reason for your visit.',
    sendFailed: 'Could not register the visit. Please try again.',

    notes: {
      'Financial Assistance': 'Funding, grants and scheme support',
      'Space Requirement': 'Desks, cabins and incubation space',
      'Fab Lab': 'Prototyping and fabrication access',
      'Maker Village': 'Hardware and electronics programmes',
      'General Enquiry': 'Anything else — we will route you',
      Meeting: 'A scheduled or walk-in meeting',
      Interview: 'Attending a job interview',
      Internship: 'Internship joining or discussion',
      'Repair/Maintenance': 'Service, repair or installation work',
      Other: 'Something else — tell us below',
    },
    labels: {
      'Financial Assistance': 'Financial Assistance',
      'Space Requirement': 'Space Requirement',
      'Fab Lab': 'Fab Lab',
      'Maker Village': 'Maker Village',
      'General Enquiry': 'General Enquiry',
      Meeting: 'Meeting',
      Interview: 'Interview',
      Internship: 'Internship',
      'Repair/Maintenance': 'Repair/Maintenance',
      Other: 'Other',
    },
    keys: {
      visit: 'Visit',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      org: 'Organisation',
      company: 'Visiting',
      purpose: 'Purpose',
    },
  },

  ml: {
    kicker: 'ഡിജിറ്റൽ റിസപ്ഷൻ',
    langTitle: 'ഭാഷ തിരഞ്ഞെടുക്കുക',

    visitTitle: 'ആരെയാണ് സന്ദർശിക്കുന്നത്?',
    visitSub: 'ആരെ അറിയിക്കണമെന്ന് ഇത് ഞങ്ങളോട് പറയുന്നു.',
    visitLabels: {
      KSUM: 'കേരള സ്റ്റാർട്ടപ്പ് മിഷൻ',
      'Incubated Company': 'ഇൻകുബേറ്റഡ് കമ്പനി',
    },
    visitNotes: {
      KSUM: 'ഫണ്ടിംഗ്, സ്ഥലം, ലാബുകൾ, പൊതു അന്വേഷണങ്ങൾ',
      'Incubated Company': 'ഈ കെട്ടിടത്തിലുള്ള ഒരു സ്റ്റാർട്ടപ്പ്',
    },

    detailsTitle: 'നിങ്ങളുടെ വിവരങ്ങൾ',
    detailsSub: 'ഇന്ന് സന്ദർശിക്കുന്നത് ആരാണെന്ന് അറിയിക്കുക.',
    name: 'പൂർണ്ണ നാമം',
    namePh: 'ഉദാ. റിച്ചാർഡ് ഹെൻഡ്രിക്സ്',
    phone: 'ഫോൺ നമ്പർ',
    phonePh: '10 അക്ക മൊബൈൽ നമ്പർ',
    email: 'ഇമെയിൽ',
    emailPh: 'name@example.com',
    org: 'സ്ഥാപനം',
    orgPh: 'കമ്പനി, കോളേജ് അല്ലെങ്കിൽ സ്ഥാപനം',
    company: 'സന്ദർശിക്കുന്ന കമ്പനി',
    companyPh: 'സ്റ്റാർട്ടപ്പിന്റെ പേര്',

    purposeTitle: 'സന്ദർശന ഉദ്ദേശ്യം',
    purposeSub: 'ഏറ്റവും അനുയോജ്യമായത് തിരഞ്ഞെടുക്കുക.',
    otherPh: 'സന്ദർശന കാരണം ചുരുക്കി എഴുതുക',

    reviewTitle: 'പരിശോധിച്ച് സ്ഥിരീകരിക്കുക',
    reviewSub: 'ചെക്ക് ഇൻ ചെയ്യുന്നതിന് മുൻപ് വിവരങ്ങൾ പരിശോധിക്കുക.',
    sheet: 'സന്ദർശക വിവരപത്രിക',

    thanks: 'നന്ദി',
    doneSub: 'ഞങ്ങളുടെ പ്രതിനിധി ഉടൻ നിങ്ങളെ കാണും. ദയവായി ലോബിയിൽ കാത്തിരിക്കുക.',
    doneSubIncubated:
      'ദയവായി ലോബിയിൽ കാത്തിരിക്കുക, തുടരാൻ കമ്പനിയുടെ പ്രതിനിധിയുമായി ബന്ധപ്പെടുക.',
    token: 'ടോക്കൺ',
    checkedIn: 'ചെക്ക് ഇൻ ചെയ്തത്',
    contactTitle: 'നിങ്ങളെ സഹായിക്കുന്ന വ്യക്തി',
    escalateIn: 'നിങ്ങളുടെ ഏകദേശ കാത്തിരിപ്പ് സമയം:',
    escalate: 'എസ്കലേറ്റ് ചെയ്യുക',
    escalating: 'അറിയിക്കുന്നു…',
    escalated: 'എസ്ക്കലേഷൻ നടന്നു',
    escalateFailed: 'അറിയിക്കാൻ കഴിഞ്ഞില്ല. ദയവായി റിസപ്ഷൻ ഡെസ്കിൽ സമീപിക്കുക.',
    loadingToken: 'ടോക്കൺ എടുക്കുന്നു…',
    notFoundTitle: 'കണ്ടെത്തിയില്ല',
    notFoundSub: 'ഈ ചെക്ക് ഇൻ റഫറൻസ് നിലവിലില്ല. വീണ്ടും ചെക്ക് ഇൻ ചെയ്യുക.',

    back: 'പിന്നോട്ട്',
    continue: 'തുടരുക',
    checkIn: 'ചെക്ക് ഇൻ',
    checkingIn: 'അയക്കുന്നു',
    newVisitor: 'പുതിയ സന്ദർശകൻ',

    reqVisit: 'ആരെയാണ് സന്ദർശിക്കുന്നതെന്ന് തിരഞ്ഞെടുക്കുക.',
    reqDetails: 'പേര്, ഫോൺ നമ്പർ, ഇമെയിൽ എന്നിവ നൽകുക.',
    reqCompany: 'സന്ദർശിക്കുന്ന കമ്പനിയുടെ പേര് നൽകുക.',
    reqPurpose: 'സന്ദർശന ഉദ്ദേശ്യം തിരഞ്ഞെടുക്കുക.',
    reqOther: 'സന്ദർശന കാരണം എഴുതുക.',
    sendFailed: 'രജിസ്റ്റർ ചെയ്യാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',

    notes: {
      'Financial Assistance': 'ഫണ്ടിംഗ്, ഗ്രാന്റ്, പദ്ധതി സഹായം',
      'Space Requirement': 'ഡെസ്ക്, ക്യാബിൻ, ഇൻകുബേഷൻ സ്ഥലം',
      'Fab Lab': 'പ്രോട്ടോടൈപ്പിംഗ്, ഫാബ്രിക്കേഷൻ സൗകര്യം',
      'Maker Village': 'ഹാർഡ്‌വെയർ, ഇലക്ട്രോണിക്സ് പ്രോഗ്രാമുകൾ',
      'General Enquiry': 'മറ്റെന്തും — ഞങ്ങൾ വഴികാട്ടും',
      Meeting: 'നിശ്ചയിച്ചതോ അല്ലാത്തതോ ആയ കൂടിക്കാഴ്ച',
      Interview: 'ജോലി അഭിമുഖത്തിന് ഹാജരാകുന്നു',
      Internship: 'ഇന്റേൺഷിപ്പ് ചേരൽ അല്ലെങ്കിൽ ചർച്ച',
      'Repair/Maintenance': 'സർവീസ്, അറ്റകുറ്റപ്പണി, ഇൻസ്റ്റാളേഷൻ',
      Other: 'മറ്റെന്തെങ്കിലും — താഴെ എഴുതുക',
    },
    labels: {
      'Financial Assistance': 'സാമ്പത്തിക സഹായം',
      'Space Requirement': 'സ്ഥല ആവശ്യകത',
      'Fab Lab': 'ഫാബ് ലാബ്',
      'Maker Village': 'മേക്കർ വില്ലേജ്',
      'General Enquiry': 'പൊതു അന്വേഷണം',
      Meeting: 'മീറ്റിംഗ്',
      Interview: 'അഭിമുഖം',
      Internship: 'ഇന്റേൺഷിപ്പ്',
      'Repair/Maintenance': 'അറ്റകുറ്റപ്പണി',
      Other: 'മറ്റുള്ളവ',
    },
    keys: {
      visit: 'സന്ദർശനം',
      name: 'പേര്',
      phone: 'ഫോൺ',
      email: 'ഇമെയിൽ',
      org: 'സ്ഥാപനം',
      company: 'സന്ദർശിക്കുന്നത്',
      purpose: 'ഉദ്ദേശ്യം',
    },
  },
}
