// Canonical purpose values — always sent to the API in English
export const PURPOSES = [
  'Financial Assistance',
  'Space Requirement',
  'Fab Lab',
  'Maker Village',
  'General Enquiry',
]

export const COPY = {
  en: {
    kicker: 'Digital Reception',
    stepTwo: 'Step 02 / 04',
    stepThree: 'Step 03 / 04',
    stepFour: 'Step 04 / 04',
    confirmed: 'Visit registered',
    rail: ['Language', 'Visitor details', 'Purpose of visit', 'Confirm'],
    langTitle: 'Select your language',
    detailsTitle: 'Your details',
    detailsSub: 'Please tell us who is visiting today.',
    name: 'Full name',
    namePh: 'e.g. Richard Hendrix',
    phone: 'Phone',
    phonePh: '10-digit mobile number',
    email: 'Email',
    emailPh: 'name@example.com',
    org: 'Organisation',
    orgPh: 'Company, college or institution',
    purposeTitle: 'Purpose of visit',
    purposeSub: 'Choose the one that fits best.',
    reviewTitle: 'Review and confirm',
    reviewSub: 'Check the sheet below before you check in.',
    sheet: 'Visitor sheet',
    thanks: 'Thank you',
    doneSub: 'Our representative will meet you shortly. Kindly wait in the lobby area.',
    token: 'Token',
    back: 'Back',
    continue: 'Continue',
    checkIn: 'Check in',
    checkingIn: 'Checking in',
    newVisitor: 'New visitor',
    reqDetails: 'Please enter your name and either a phone number or an email.',
    reqPurpose: 'Please select a purpose of visit.',
    sendFailed: 'Could not register the visit. Please try again.',
    notes: [
      'Funding, grants and scheme support',
      'Desks, cabins and incubation space',
      'Prototyping and fabrication access',
      'Hardware and electronics programmes',
      'Anything else — we will route you',
    ],
    labels: {
      'Financial Assistance': 'Financial Assistance',
      'Space Requirement': 'Space Requirement',
      'Fab Lab': 'Fab Lab',
      'Maker Village': 'Maker Village',
      'General Enquiry': 'General Enquiry',
    },
    keys: ['Name', 'Phone', 'Email', 'Organisation', 'Purpose'],
  },
  ml: {
    kicker: 'ഡിജിറ്റൽ റിസപ്ഷൻ',
    stepTwo: 'ഘട്ടം 02 / 04',
    stepThree: 'ഘട്ടം 03 / 04',
    stepFour: 'ഘട്ടം 04 / 04',
    confirmed: 'സന്ദർശനം രജിസ്റ്റർ ചെയ്തു',
    rail: ['ഭാഷ', 'സന്ദർശക വിവരങ്ങൾ', 'സന്ദർശന ഉദ്ദേശ്യം', 'സ്ഥിരീകരിക്കുക'],
    langTitle: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    detailsTitle: 'നിങ്ങളുടെ വിവരങ്ങൾ',
    detailsSub: 'ഇന്ന് സന്ദർശിക്കുന്നത് ആരാണെന്ന് അറിയിക്കുക.',
    name: 'പൂർണ്ണ നാമം',
    namePh: 'ഉദാ. റിച്ചാർഡ് ഹെൻഡ്രിക്സ്',
    phone: 'ഫോൺ നമ്പർ',
    phonePh: '10 അക്ക മൊബൈൽ നമ്പർ',
    email: 'ഇമെയിൽ',
    emailPh: 'name@example.com',
    org: 'സ്ഥാപനം',
    orgPh: 'കമ്പനി, കോളേജ് അല്ലെങ്കിൽ സ്ഥാപനം',
    purposeTitle: 'സന്ദർശന ഉദ്ദേശ്യം',
    purposeSub: 'ഏറ്റവും അനുയോജ്യമായത് തിരഞ്ഞെടുക്കുക.',
    reviewTitle: 'പരിശോധിച്ച് സ്ഥിരീകരിക്കുക',
    reviewSub: 'ചെക്ക് ഇൻ ചെയ്യുന്നതിന് മുൻപ് വിവരങ്ങൾ പരിശോധിക്കുക.',
    sheet: 'സന്ദർശക വിവരപത്രിക',
    thanks: 'നന്ദി',
    doneSub: 'ഞങ്ങളുടെ പ്രതിനിധി ഉടൻ നിങ്ങളെ കാണും. ദയവായി ലോബിയിൽ കാത്തിരിക്കുക.',
    token: 'ടോക്കൺ',
    back: 'പിന്നോട്ട്',
    continue: 'തുടരുക',
    checkIn: 'ചെക്ക് ഇൻ',
    checkingIn: 'അയക്കുന്നു',
    newVisitor: 'പുതിയ സന്ദർശകൻ',
    reqDetails: 'പേരും, ഫോൺ നമ്പറോ ഇമെയിലോ നൽകുക.',
    reqPurpose: 'സന്ദർശന ഉദ്ദേശ്യം തിരഞ്ഞെടുക്കുക.',
    sendFailed: 'രജിസ്റ്റർ ചെയ്യാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    notes: [
      'ഫണ്ടിംഗ്, ഗ്രാന്റ്, പദ്ധതി സഹായം',
      'ഡെസ്ക്, ക്യാബിൻ, ഇൻകുബേഷൻ സ്ഥലം',
      'പ്രോട്ടോടൈപ്പിംഗ്, ഫാബ്രിക്കേഷൻ സൗകര്യം',
      'ഹാർഡ്‌വെയർ, ഇലക്ട്രോണിക്സ് പ്രോഗ്രാമുകൾ',
      'മറ്റെന്തും — ഞങ്ങൾ വഴികാട്ടും',
    ],
    labels: {
      'Financial Assistance': 'സാമ്പത്തിക സഹായം',
      'Space Requirement': 'സ്ഥല ആവശ്യകത',
      'Fab Lab': 'ഫാബ് ലാബ്',
      'Maker Village': 'മേക്കർ വില്ലേജ്',
      'General Enquiry': 'പൊതു അന്വേഷണം',
    },
    keys: ['പേര്', 'ഫോൺ', 'ഇമെയിൽ', 'സ്ഥാപനം', 'ഉദ്ദേശ്യം'],
  },
}
